title: Ram Prasad Meenavalli
email: ram@meenavalli.in
author: Ram Prasad
copyright: 'Copyright Â© 2011-2020'
description: ''
baseurl: ''
favicon: '/assets/images/Ram.png'
url: 'https://blog.meenavalli.in'
twitter_username: ram_meenavalli
github_username: RamPrasadMeenavalli
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-spaceship

# Author Bio settings
profile-photo: '/assets/images/Ram.png'
profile-name: Ram Prasad
profile-url: https://meenavalli.in
profile-tagline: Developer | Office 365 | SharePoint | Blogger | Speaker
profile-fb: https://www.facebook.com/ramprasad.meenavalli
profile-twitter: https://twitter.com/ram_meenavalli
profile-linkedin: https://www.linkedin.com/in/ramprasadmeenavalli/
profile-youtube: https://www.youtube.com/channel/UCBp4idRQxYfnJTPugX40dwg

google_analytics: UA-55279237-1

# If you don't want transparent header, you can set false
header_transparent: false

# Pagination setting
paginate: 4

fbappid: 1406604756269400

header_pages:
  - index.html
  - talks.html